# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:48:43+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer
from fastapi import Query

from models import CallLogsHalResponse, Direction, ValidationErrorsResponse

app = MCPProxy(
    contact={
        'name': 'Vonage Business Cloud Support',
        'url': 'https://businesssupport.vonage.com/contactus',
    },
    description='The Vonage Business Cloud Reports API enables you to retrieve call logs for your account.\n\nYour application must subscribe to the Reports API suite to use this API.\n',
    termsOfService='https://www.vonage.com/business/legal-policy-center/business-cloud/tos',
    title='Reports API',
    version='1.0.1',
    servers=[{'url': 'https://api.vonage.com/t/vbc.prod/reports'}],
)


@app.get(
    '/accounts/{account_id}/call-logs',
    description=""" Retrieve call logs for your account """,
    tags=['call_log_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_call_logs(
    account_id: str,
    start_gte: str = Query(..., alias='start:gte'),
    start_lte: str = Query(..., alias='start:lte'),
    end_gte: Optional[str] = Query(None, alias='end:gte'),
    end_lte: Optional[str] = Query(None, alias='end:lte'),
    page_size: float = 10,
    page: float = 0,
    to: Optional[str] = None,
    from_: Optional[str] = Query(None, alias='from'),
    source_user: Optional[str] = None,
    destination_user: Optional[str] = None,
    direction: Optional[Direction] = None,
):
    """
    Retrieve call logs for your account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
