# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:48:43+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class CallLog(BaseModel):
    charge: Optional[float] = Field(
        None, description='Amount charged for the call', examples=[0]
    )
    destination_device_name: Optional[str] = Field(
        None,
        description='Name of the destination device of the call',
        examples=['Smith'],
    )
    destination_extension: Optional[float] = Field(
        None, description='Destination extension of the call', examples=[1000]
    )
    destination_sip_id: Optional[str] = Field(
        None,
        description='SIP ID of the destination device of the call',
        examples=['VH1111111'],
    )
    destination_user: Optional[str] = Field(
        None, description='Destination user of the call', examples=['JSmith']
    )
    destination_user_full_name: Optional[str] = Field(
        None,
        description='Full name of the destination user of the call',
        examples=['John Smith'],
    )
    direction: Optional[str] = Field(
        None, description='Direction of the call', examples=['Inbound']
    )
    end: Optional[str] = Field(
        None, description='End time of the call', examples=['2019-01-01 00:00:00']
    )
    from_: Optional[str] = Field(
        None,
        alias='from',
        description='Source number of the call',
        examples=[17325550100],
    )
    id: Optional[str] = Field(
        None,
        description='Unique identifier of the call',
        examples=['f27b937d-6dde-441a-9595-006e7302eac1'],
    )
    in_network: Optional[bool] = Field(
        None, description='Indicates if call was on/off network', examples=[True]
    )
    international: Optional[bool] = Field(
        None, description='Indicates if call was international', examples=[False]
    )
    length: Optional[float] = Field(
        None, description='Duration of the call in seconds', examples=[60]
    )
    rate: Optional[float] = Field(
        None, description='Rate charged for the call', examples=[0]
    )
    recorded: Optional[bool] = Field(
        None, description='Indicates if call was recorded', examples=[True]
    )
    result: Optional[str] = Field(
        None, description='Result of the call', examples=['Answered']
    )
    source_device_name: Optional[str] = Field(
        None, description='Name of the source device of the call', examples=['Smith']
    )
    source_extension: Optional[float] = Field(
        None, description='Source extension of the call', examples=[1000]
    )
    source_sip_id: Optional[str] = Field(
        None,
        description='SIP ID of the source device of the call',
        examples=['VH1111111'],
    )
    source_user: Optional[str] = Field(
        None, description='Source user of the call', examples=['JSmith']
    )
    source_user_full_name: Optional[str] = Field(
        None,
        description='Full name of the source user of the call',
        examples=['John Smith'],
    )
    start: Optional[str] = Field(
        None, description='Start time of the call', examples=['2019-01-01 00:00:00']
    )
    to: Optional[str] = Field(
        None, description='Destination number of the call', examples=[17325550100]
    )


class CallLogsEmbeddedObject(BaseModel):
    call_logs: Optional[List[CallLog]] = None


class DetailedInvalidParam(BaseModel):
    name: Optional[str] = Field(None, description='Invalid property name')
    reason: Optional[str] = Field(None, description='Invalid property reason')


class ErrorResponse(BaseModel):
    msg: Optional[str] = Field(None, description='Error message')
    status: Optional[float] = Field(None, description='Http Response Code')


class FirstHref(BaseModel):
    href: Optional[str] = None


class LastHref(BaseModel):
    href: Optional[str] = None


class NextHref(BaseModel):
    href: Optional[str] = None


class PrevHref(BaseModel):
    href: Optional[str] = None


class SelfHref(BaseModel):
    href: Optional[str] = None


class ValidationErrorsResponse(BaseModel):
    instance: Optional[str] = Field(None, description='Error Track ID')
    invalid_parameters: Optional[List[DetailedInvalidParam]] = Field(
        None, description='Invalid parameters and their reason for failing'
    )
    status: Optional[float] = Field(None, description='Error status code')
    title: Optional[str] = Field(None, description='Error title')


class Direction(Enum):
    Inbound = 'Inbound'
    Outbound = 'Outbound'


class Links(BaseModel):
    first: Optional[FirstHref] = None
    next: Optional[NextHref] = None
    prev: Optional[PrevHref] = None
    self: Optional[SelfHref] = None


class CallLogsHalResponse(BaseModel):
    field_embedded: Optional[CallLogsEmbeddedObject] = Field(None, alias='_embedded')
    field_links: Optional[Links] = Field(None, alias='_links')
    page: Optional[float] = Field(None, description='Current page number', examples=[1])
    page_size: Optional[float] = Field(
        None, description='Number of records per page', examples=[10]
    )
    total_items: Optional[float] = Field(
        None, description='Total number of records', examples=[100]
    )
    total_page: Optional[float] = Field(
        None, description='Total number of pages', examples=[10]
    )
